import { createHash } from "node:crypto";
import type { BuildManifest, ProgramIr } from "./model.js";
import { entityTableName } from "./generator.js";
import type { GeneratedUi } from "./ui-codegen.js";
import { SCOUT_THEME_SCRIPT, THEME_SCRIPT } from "./ui-codegen.js";

export interface GeneratedRuntime {
  appMjs: string;
  packageJson: string;
}

function cspHash(value: string): string {
  return `sha256-${createHash("sha256").update(value, "utf8").digest("base64")}`;
}

export function generateRuntime(
  ir: ProgramIr,
  manifest: BuildManifest,
  ui: GeneratedUi
): GeneratedRuntime {
  const tableByEntityId = Object.fromEntries(
    ir.entities.map((entity) => [entity.id, entityTableName(entity.name)])
  );
  const schemaJson = JSON.stringify(ir);
  const tableMapJson = JSON.stringify(tableByEntityId);
  const indexHtml = JSON.stringify(ui.indexHtml);
  const appJs = JSON.stringify(ui.appJs);
  const stylesCss = JSON.stringify(ui.stylesCss);
  const cspThemeHash = cspHash(THEME_SCRIPT);
  const cspScoutHash = cspHash(SCOUT_THEME_SCRIPT);
  const appMjs = `// Generated by IntentLang compiler v${manifest.compilerVersion}
import { createServer } from 'node:http';
import { readFileSync } from 'node:fs';
import { createHash, randomBytes, randomUUID, scrypt, timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';
import { DatabaseSync } from 'node:sqlite';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const scryptAsync = promisify(scrypt);
const __dirname = dirname(fileURLToPath(import.meta.url));
const manifest = JSON.parse(readFileSync(join(__dirname, 'intentlang.manifest.json'), 'utf8'));
const migrationSql = readFileSync(join(__dirname, 'migration.sql'), 'utf8');
const INDEX_HTML = ${indexHtml};
const APP_JS = ${appJs};
const STYLES_CSS = ${stylesCss};
const SECURITY_SCHEMA = ${schemaJson};
const ENTITY_TABLES = ${tableMapJson};
const DB_PATH = join(__dirname, 'app.sqlite');
const PORT = Number(process.env['PORT'] ?? '3210');
const META_TABLE = '__intentlang_meta';
const IDEMPOTENCY_TABLE = '__intentlang_idempotency';
const ACCOUNTS_TABLE = '__intentlang_accounts';
const SESSIONS_TABLE = '__intentlang_sessions';
const AUDIT_TABLE = '__intentlang_audit';
const SESSION_COOKIE_NAME = 'session';
const SESSION_MAX_AGE_SECONDS = 28800;
const SESSION_COOKIE_SECURE = String(process.env['INTENTLANG_COOKIE_SECURE'] ?? '') === 'true';
const LOGIN_LIMIT_MAX = 10;
const LOGIN_LIMIT_WINDOW_MS = 60_000;
const LOGIN_ATTEMPTS = new Map();
const SESSION_CSRF_TOKENS = new Map();
const FIRST_ACCOUNT_ERROR = 'ERROR: No accounts exist. Set INTENTLANG_BOOTSTRAP_NAME, INTENTLANG_BOOTSTRAP_EMAIL, and INTENTLANG_BOOTSTRAP_PASSWORD to create the first Administrator account.';
const EXACT_ACCOUNT_COLUMNS = ['identity_id','role_id','password_salt','password_hash','scrypt_n','scrypt_r','scrypt_p','scrypt_keylen','password_version','disabled','created_at','updated_at'];
const EXACT_SESSION_COLUMNS = ['token_hash','csrf_token_hash','identity_id','role_id','expires_at','created_at','last_seen_at','revoked_at'];
const EXACT_AUDIT_COLUMNS = ['id','actor_identity_id','actor_role_id','operation','target_entity','target_id','outcome','cause','idempotency_key','before_json','after_json','ir_fingerprint','created_at'];
const db = new DatabaseSync(DB_PATH);
db.exec('PRAGMA foreign_keys = ON');
db.exec('PRAGMA journal_mode = WAL');
await initialize();

function makeNonce(){
  return randomBytes(16).toString('base64');
}

function nowIso(){
  return new Date().toISOString();
}

function sha256(value){
  return createHash('sha256').update(value, 'utf8').digest('hex');
}

function normalizeEmail(value){
  return String(value ?? '').trim().toLowerCase();
}

function tableExists(name){
  return db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").get(name) !== undefined;
}

function getTableColumns(name){
  if (!tableExists(name)) {
    return [];
  }
  const rows = db.prepare('PRAGMA table_info("' + name + '")').all();
  return rows.map((row) => String(row.name));
}

function hasExactColumns(name, expected){
  const actual = getTableColumns(name);
  return actual.length === expected.length && actual.every((column, index) => column === expected[index]);
}

function normalizeMigrationSql(sql){
  return sql
    .replace(/CREATE TABLE "/g, 'CREATE TABLE IF NOT EXISTS "')
    .replace(/CREATE UNIQUE INDEX "/g, 'CREATE UNIQUE INDEX IF NOT EXISTS "');
}

function setMeta(key, value){
  db.prepare('INSERT INTO "' + META_TABLE + '" ("key","value") VALUES (?,?) ON CONFLICT("key") DO UPDATE SET "value"=excluded."value"').run(key, value);
}

function getMeta(key){
  const row = db.prepare('SELECT "value" FROM "' + META_TABLE + '" WHERE "key"=?').get(key);
  return row ? String(row.value) : null;
}

function json(res, status, data, extraHeaders){
  const nonce = makeNonce();
  const body = JSON.stringify(data);
  res.writeHead(status, Object.assign({
    'Content-Type': 'application/json; charset=utf-8',
    'Content-Length': Buffer.byteLength(body)
  }, securityHeaders(nonce), extraHeaders ?? {}));
  res.end(body);
}

function html(res, body){
  const nonce = makeNonce();
  const rendered = body.replaceAll('__INTENTLANG_NONCE__', nonce);
  res.writeHead(200, Object.assign({
    'Content-Type': 'text/html; charset=utf-8',
    'Content-Length': Buffer.byteLength(rendered)
  }, securityHeaders(nonce)));
  res.end(rendered);
}

function text(res, status, contentType, body){
  const nonce = makeNonce();
  res.writeHead(status, Object.assign({
    'Content-Type': contentType,
    'Content-Length': Buffer.byteLength(body)
  }, securityHeaders(nonce)));
  res.end(body);
}

function securityHeaders(nonce){
  return {
    'X-Content-Type-Options': 'nosniff',
    'Referrer-Policy': 'no-referrer',
    'Cache-Control': 'no-store',
    'Permissions-Policy': 'camera=(), microphone=(), geolocation=()',
    'Content-Security-Policy': "default-src 'self'; script-src 'self' 'nonce-" + nonce + "' '${cspScoutHash}' '${cspThemeHash}'; style-src 'self' 'nonce-" + nonce + "'; img-src 'self'; connect-src 'self'; frame-ancestors none"
  };
}

function requireSameOrigin(req){
  const origin = req.headers['origin'];
  const host = req.headers['host'];
  if (typeof origin !== 'string' || typeof host !== 'string') {
    return { status: 403, body: { code: 'FORBIDDEN', error: 'Origin denied.' } };
  }
  if (origin !== 'http://' + host && origin !== 'https://' + host) {
    return { status: 403, body: { code: 'FORBIDDEN', error: 'Origin denied.' } };
  }
  return undefined;
}

function sessionCookie(req){
  const raw = req.headers['cookie'];
  if (typeof raw !== 'string') {
    return null;
  }
  const match = /(?:^|;\s*)session=([^;]+)/.exec(raw);
  return match ? decodeURIComponent(match[1]) : null;
}

function clearSessionMemory(tokenHash){
  SESSION_CSRF_TOKENS.delete(tokenHash);
}

function sessionCookieHeader(token, maxAgeSeconds){
  const secure = SESSION_COOKIE_SECURE ? '; Secure' : '';
  return SESSION_COOKIE_NAME + '=' + encodeURIComponent(token) + '; HttpOnly; SameSite=Strict; Path=/; Max-Age=' + String(maxAgeSeconds) + secure;
}

function authConfig(){
  if (!SECURITY_SCHEMA.authentication) {
    return null;
  }
  const identityEntity = SECURITY_SCHEMA.entities.find((entity) => entity.id === SECURITY_SCHEMA.authentication.identityEntityId);
  if (!identityEntity) {
    throw new Error('Identity entity missing from generated schema.');
  }
  const identityField = identityEntity.fields.find((field) => field.id === SECURITY_SCHEMA.authentication.identityFieldId);
  if (!identityField) {
    throw new Error('Identity field missing from generated schema.');
  }
  return {
    identityEntity,
    identityField,
    identityTable: ENTITY_TABLES[identityEntity.id]
  };
}

function permissionSetForRole(roleId){
  return (SECURITY_SCHEMA.permissions ?? []).filter((permission) => permission.roleId === roleId);
}

function effectivePermissions(roleId){
  return permissionSetForRole(roleId).map((permission) => ({
    id: permission.id,
    roleId: permission.roleId,
    operation: permission.operation,
    entityId: permission.entityId,
    ...(permission.actionId === undefined ? {} : { actionId: permission.actionId }),
    ...(permission.scope === undefined ? {} : { scope: permission.scope })
  }));
}

function ownerRelationship(entityId){
  if (!SECURITY_SCHEMA.authentication) {
    return undefined;
  }
  return (SECURITY_SCHEMA.relationships ?? []).find((relationship) =>
    relationship.fromEntityId === entityId &&
    relationship.toEntityId === SECURITY_SCHEMA.authentication.identityEntityId &&
    relationship.name === 'owner'
  );
}

function authorize(session, operation, entityId, actionId, record){
  if (!SECURITY_SCHEMA.authentication) {
    return { allowed: true, forceOwner: false };
  }
  if (!session) {
    return { allowed: false, forceOwner: false };
  }
  const candidates = permissionSetForRole(session.role_id).filter((permission) =>
    permission.operation === operation &&
    permission.entityId === entityId &&
    (actionId === undefined || permission.actionId === actionId)
  );
  if (candidates.length === 0) {
    return { allowed: false, forceOwner: false };
  }
  const forceOwner = candidates.some((permission) => permission.scope?.kind === 'force-owner');
  if (record === undefined) {
    return { allowed: true, forceOwner };
  }
  for (const permission of candidates) {
    if (!permission.scope) {
      return { allowed: true, forceOwner };
    }
    if (permission.scope.kind === 'self' && String(record.id ?? '') === session.identity_id) {
      return { allowed: true, forceOwner };
    }
    if ((permission.scope.kind === 'owner' || permission.scope.kind === 'force-owner') && String(record.owner_id ?? '') === session.identity_id) {
      return { allowed: true, forceOwner };
    }
  }
  return { allowed: false, forceOwner: false };
}

function effectiveWhere(session, entityId){
  if (!SECURITY_SCHEMA.authentication) {
    return { sql: '', params: [] };
  }
  const permissions = permissionSetForRole(session.role_id).filter((permission) => permission.operation === 'read' && permission.entityId === entityId);
  if (permissions.some((permission) => permission.scope === undefined)) {
    return { sql: '', params: [] };
  }
  const clauses = [];
  const params = [];
  for (const permission of permissions) {
    if (!permission.scope) {
      continue;
    }
    if (permission.scope.kind === 'self') {
      clauses.push('"id" = ?');
      params.push(session.identity_id);
      continue;
    }
    clauses.push('"owner_id" = ?');
    params.push(session.identity_id);
  }
  if (clauses.length === 0) {
    return { sql: '1=0', params: [] };
  }
  return { sql: clauses.join(' OR '), params };
}

function sanitizeAuditPayload(value){
  if (Array.isArray(value)) {
    return value.map((item) => sanitizeAuditPayload(item));
  }
  if (value && typeof value === 'object') {
    const out = {};
    for (const [key, nested] of Object.entries(value)) {
      const lower = key.toLowerCase();
      if (lower.includes('password') || lower.includes('token') || lower.includes('csrf') || lower.includes('session')) {
        continue;
      }
      out[key] = sanitizeAuditPayload(nested);
    }
    return out;
  }
  return value;
}

function auditLog({ actorIdentityId = null, actorRoleId = null, operation, targetEntity = null, targetId = null, outcome, cause = null, idempotencyKey = null, before = null, after = null }){
  db.prepare(
    'INSERT INTO "' + AUDIT_TABLE + '" ("id","actor_identity_id","actor_role_id","operation","target_entity","target_id","outcome","cause","idempotency_key","before_json","after_json","ir_fingerprint","created_at") VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)'
  ).run(
    randomUUID(),
    actorIdentityId,
    actorRoleId,
    operation,
    targetEntity,
    targetId,
    outcome,
    cause,
    idempotencyKey,
    before === null ? null : JSON.stringify(sanitizeAuditPayload(before)),
    after === null ? null : JSON.stringify(sanitizeAuditPayload(after)),
    manifest.irFingerprint,
    nowIso()
  );
}

async function passwordHash(password, saltHex, params){
  const salt = Buffer.from(saltHex, 'hex');
  const options = params ?? { N: 16384, r: 8, p: 1, keylen: 64 };
  const derived = await scryptAsync(password, salt, options.keylen, { N: options.N, r: options.r, p: options.p });
  return Buffer.from(derived).toString('hex');
}

function readBody(req){
  return new Promise((resolve, reject) => {
    const chunks = [];
    req.on('data', (chunk) => chunks.push(chunk));
    req.on('end', () => {
      const raw = Buffer.concat(chunks).toString('utf8');
      if (raw === '') {
        resolve({});
        return;
      }
      try {
        resolve(JSON.parse(raw));
      } catch (error) {
        reject(error);
      }
    });
    req.on('error', reject);
  });
}

function normalizeBoolean(value){
  if (value === true || value === false) {
    return value ? 1 : 0;
  }
  if (value === 1 || value === 0) {
    return value;
  }
  return value;
}

function loginBucketKey(email, remote){
  return email + '|' + remote;
}

function loginAllowed(email, remote){
  const key = loginBucketKey(email, remote);
  const now = Date.now();
  const prior = LOGIN_ATTEMPTS.get(key) ?? [];
  const fresh = prior.filter((timestamp) => now - timestamp < LOGIN_LIMIT_WINDOW_MS);
  if (fresh.length >= LOGIN_LIMIT_MAX) {
    LOGIN_ATTEMPTS.set(key, fresh);
    return false;
  }
  fresh.push(now);
  LOGIN_ATTEMPTS.set(key, fresh);
  return true;
}

function rememberCsrf(tokenHash, csrfToken){
  SESSION_CSRF_TOKENS.set(tokenHash, csrfToken);
}

function ensureCsrfToken(session){
  const remembered = SESSION_CSRF_TOKENS.get(session.token_hash);
  if (typeof remembered === 'string') {
    return remembered;
  }
  const next = randomBytes(16).toString('hex');
  const nextHash = sha256(next);
  db.prepare('UPDATE "' + SESSIONS_TABLE + '" SET "csrf_token_hash"=? WHERE "token_hash"=?').run(nextHash, session.token_hash);
  session.csrf_token_hash = nextHash;
  rememberCsrf(session.token_hash, next);
  return next;
}

function validateCsrf(session, req){
  const header = req.headers['x-csrf-token'];
  if (typeof header !== 'string') {
    return { status: 403, body: { code: 'FORBIDDEN', error: 'Missing CSRF token.' } };
  }
  const left = Buffer.from(String(session.csrf_token_hash), 'hex');
  const right = Buffer.from(sha256(header), 'hex');
  if (left.length !== right.length || !timingSafeEqual(left, right)) {
    return { status: 403, body: { code: 'FORBIDDEN', error: 'Invalid CSRF token.' } };
  }
  rememberCsrf(session.token_hash, header);
  return undefined;
}

function validateSession(req){
  if (!SECURITY_SCHEMA.authentication) {
    return undefined;
  }
  const token = sessionCookie(req);
  if (!token) {
    return undefined;
  }
  const tokenHash = sha256(token);
  const row = db.prepare(
    'SELECT s."token_hash", s."csrf_token_hash", s."identity_id", s."role_id", s."expires_at", s."created_at", s."last_seen_at", s."revoked_at", a."disabled" FROM "' + SESSIONS_TABLE + '" s JOIN "' + ACCOUNTS_TABLE + '" a ON a."identity_id" = s."identity_id" WHERE s."token_hash"=?'
  ).get(tokenHash);
  if (!row) {
    return undefined;
  }
  if (row.revoked_at !== null) {
    clearSessionMemory(tokenHash);
    return undefined;
  }
  if (Date.parse(String(row.expires_at)) <= Date.now()) {
    clearSessionMemory(tokenHash);
    return undefined;
  }
  if (Number(row.disabled) === 1) {
    db.prepare('UPDATE "' + SESSIONS_TABLE + '" SET "revoked_at"=? WHERE "token_hash"=? AND "revoked_at" IS NULL').run(nowIso(), tokenHash);
    clearSessionMemory(tokenHash);
    return undefined;
  }
  db.prepare('UPDATE "' + SESSIONS_TABLE + '" SET "last_seen_at"=? WHERE "token_hash"=?').run(nowIso(), tokenHash);
  return {
    token,
    token_hash: tokenHash,
    csrf_token_hash: String(row.csrf_token_hash),
    identity_id: String(row.identity_id),
    role_id: String(row.role_id),
    expires_at: String(row.expires_at),
    created_at: String(row.created_at),
    last_seen_at: String(row.last_seen_at),
    revoked_at: row.revoked_at === null ? null : String(row.revoked_at)
  };
}

function idempotencyRecord(scope, operationKey){
  return db.prepare('SELECT * FROM "' + IDEMPOTENCY_TABLE + '" WHERE "scope"=? AND "operation_key"=?').get(scope, operationKey);
}

function replayIdempotency(res, scope, operationKey, fingerprint){
  const existing = idempotencyRecord(scope, operationKey);
  if (!existing) {
    return false;
  }
  if (String(existing.request_fingerprint) !== fingerprint) {
    json(res, 409, { code: 'IDEMPOTENCY_KEY_REUSED', error: 'Idempotency-Key was already used with a different request body.' });
    return true;
  }
  json(res, Number(existing.status_code), JSON.parse(String(existing.response_json)), { 'Idempotency-Replayed': 'true' });
  return true;
}

function storeIdempotency(scope, operationKey, fingerprint, recordId, statusCode, responseBody){
  db.prepare(
    'INSERT INTO "' + IDEMPOTENCY_TABLE + '" ("scope","operation_key","request_fingerprint","record_id","status_code","response_json") VALUES (?,?,?,?,?,?)'
  ).run(scope, operationKey, fingerprint, recordId, statusCode, JSON.stringify(responseBody));
}

function typedFieldValue(field, bodyValue){
  if (field.type === 'boolean') {
    return normalizeBoolean(bodyValue);
  }
  return bodyValue;
}

function buildIdentityValues(body){
  const config = authConfig();
  if (!config) {
    throw new Error('Authentication is not enabled.');
  }
  const identityId = randomUUID();
  const now = nowIso();
  const columns = ['id', 'created_at', 'updated_at', 'version'];
  const values = [identityId, now, now, 1];
  for (const field of config.identityEntity.fields) {
    let rawValue;
    if (field.name === config.identityField.name) {
      rawValue = normalizeEmail(body[field.name]);
    } else {
      rawValue = body[field.name];
    }
    if ((rawValue === undefined || rawValue === null || rawValue === '') && field.default !== undefined) {
      rawValue = field.default;
    }
    if (field.required && (rawValue === undefined || rawValue === null || rawValue === '')) {
      throw new Error('VALIDATION_ERROR:' + field.name);
    }
    columns.push(field.name);
    values.push(rawValue === undefined ? null : typedFieldValue(field, rawValue));
  }
  return { identityId, now, columns, values, config };
}

function bootstrapRoleId(){
  const admin = (SECURITY_SCHEMA.roles ?? []).find((role) => role.name === 'Administrator');
  if (admin) {
    return admin.id;
  }
  const first = SECURITY_SCHEMA.roles?.[0];
  if (!first) {
    throw new Error('No roles are defined for bootstrap.');
  }
  return first.id;
}

async function bootstrapFirstAccount(){
  const row = db.prepare('SELECT COUNT(*) AS count FROM "' + ACCOUNTS_TABLE + '"').get();
  const count = Number(row?.count ?? 0);
  if (count > 0) {
    return;
  }
  const name = String(process.env['INTENTLANG_BOOTSTRAP_NAME'] ?? '').trim();
  const email = normalizeEmail(process.env['INTENTLANG_BOOTSTRAP_EMAIL'] ?? '');
  const password = String(process.env['INTENTLANG_BOOTSTRAP_PASSWORD'] ?? '');
  if (!name || !email || !password) {
    console.error(FIRST_ACCOUNT_ERROR);
    process.exit(1);
  }
  if (password.length < 12) {
    console.error('ERROR: INTENTLANG_BOOTSTRAP_PASSWORD must be at least 12 characters.');
    process.exit(1);
  }
  const { identityId, now, columns, values, config } = buildIdentityValues({ name, [authConfig().identityField.name]: email });
  const roleId = bootstrapRoleId();
  const salt = randomBytes(32).toString('hex');
  const hash = await passwordHash(password, salt);
  db.exec('BEGIN');
  try {
    db.prepare('INSERT INTO "' + config.identityTable + '" (' + columns.map((column) => '"' + column + '"').join(',') + ') VALUES (' + columns.map(() => '?').join(',') + ')').run(...values);
    db.prepare(
      'INSERT INTO "' + ACCOUNTS_TABLE + '" ("identity_id","role_id","password_salt","password_hash","scrypt_n","scrypt_r","scrypt_p","scrypt_keylen","password_version","disabled","created_at","updated_at") VALUES (?,?,?,?,16384,8,1,64,1,0,?,?)'
    ).run(identityId, roleId, salt, hash, now, now);
    auditLog({
      actorIdentityId: identityId,
      actorRoleId: roleId,
      operation: 'auth.bootstrap',
      targetEntity: config.identityEntity.id,
      targetId: identityId,
      outcome: 'allowed',
      after: { identity_id: identityId, role_id: roleId, identity_email: email, identity_name: name }
    });
    db.exec('COMMIT');
  } catch (error) {
    db.exec('ROLLBACK');
    throw error;
  }
}

function ensureAccountsTable(){
  const createSql = 'CREATE TABLE "' + ACCOUNTS_TABLE + '" ("identity_id" TEXT NOT NULL UNIQUE,"role_id" TEXT NOT NULL,"password_salt" TEXT NOT NULL,"password_hash" TEXT NOT NULL,"scrypt_n" INTEGER NOT NULL DEFAULT 16384,"scrypt_r" INTEGER NOT NULL DEFAULT 8,"scrypt_p" INTEGER NOT NULL DEFAULT 1,"scrypt_keylen" INTEGER NOT NULL DEFAULT 64,"password_version" INTEGER NOT NULL DEFAULT 1,"disabled" INTEGER NOT NULL DEFAULT 0 CHECK(disabled IN(0,1)),"created_at" TEXT NOT NULL,"updated_at" TEXT NOT NULL)';
  if (!tableExists(ACCOUNTS_TABLE)) {
    db.exec(createSql);
    return;
  }
  if (hasExactColumns(ACCOUNTS_TABLE, EXACT_ACCOUNT_COLUMNS)) {
    return;
  }
  const temp = '__intentlang_accounts_legacy';
  if (tableExists(temp)) {
    db.exec('DROP TABLE "' + temp + '"');
  }
  db.exec('ALTER TABLE "' + ACCOUNTS_TABLE + '" RENAME TO "' + temp + '"');
  db.exec(createSql);
  const rows = db.prepare('SELECT * FROM "' + temp + '"').all();
  for (const row of rows) {
    db.prepare(
      'INSERT INTO "' + ACCOUNTS_TABLE + '" ("identity_id","role_id","password_salt","password_hash","scrypt_n","scrypt_r","scrypt_p","scrypt_keylen","password_version","disabled","created_at","updated_at") VALUES (?,?,?,?,?,?,?,?,?,?,?,?)'
    ).run(
      String(row.identity_id),
      String(row.role_id),
      String(row.password_salt),
      String(row.password_hash),
      Number(row.scrypt_n ?? 16384),
      Number(row.scrypt_r ?? 8),
      Number(row.scrypt_p ?? 1),
      Number(row.scrypt_keylen ?? 64),
      Number(row.password_version ?? 1),
      Number(row.disabled ?? 0),
      String(row.created_at),
      String(row.updated_at)
    );
  }
  db.exec('DROP TABLE "' + temp + '"');
}

function ensureSessionsTable(){
  const createSql = 'CREATE TABLE "' + SESSIONS_TABLE + '" ("token_hash" TEXT PRIMARY KEY,"csrf_token_hash" TEXT NOT NULL,"identity_id" TEXT NOT NULL,"role_id" TEXT NOT NULL,"expires_at" TEXT NOT NULL,"created_at" TEXT NOT NULL,"last_seen_at" TEXT NOT NULL,"revoked_at" TEXT)';
  if (!tableExists(SESSIONS_TABLE)) {
    db.exec(createSql);
    return;
  }
  if (hasExactColumns(SESSIONS_TABLE, EXACT_SESSION_COLUMNS)) {
    return;
  }
  db.exec('DROP TABLE "' + SESSIONS_TABLE + '"');
  db.exec(createSql);
}

function ensureAuditTable(){
  const createSql = 'CREATE TABLE "' + AUDIT_TABLE + '" ("id" TEXT PRIMARY KEY,"actor_identity_id" TEXT,"actor_role_id" TEXT,"operation" TEXT NOT NULL,"target_entity" TEXT,"target_id" TEXT,"outcome" TEXT NOT NULL,"cause" TEXT,"idempotency_key" TEXT,"before_json" TEXT,"after_json" TEXT,"ir_fingerprint" TEXT NOT NULL,"created_at" TEXT NOT NULL)';
  if (!tableExists(AUDIT_TABLE)) {
    db.exec(createSql);
    return;
  }
  if (hasExactColumns(AUDIT_TABLE, EXACT_AUDIT_COLUMNS)) {
    return;
  }
  const temp = '__intentlang_audit_legacy';
  if (tableExists(temp)) {
    db.exec('DROP TABLE "' + temp + '"');
  }
  db.exec('ALTER TABLE "' + AUDIT_TABLE + '" RENAME TO "' + temp + '"');
  db.exec(createSql);
  const rows = db.prepare('SELECT * FROM "' + temp + '"').all();
  for (const row of rows) {
    db.prepare(
      'INSERT INTO "' + AUDIT_TABLE + '" ("id","actor_identity_id","actor_role_id","operation","target_entity","target_id","outcome","cause","idempotency_key","before_json","after_json","ir_fingerprint","created_at") VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)'
    ).run(
      String(row.id ?? randomUUID()),
      row.actor_identity_id ?? null,
      row.actor_role_id ?? null,
      String(row.operation ?? row.action ?? 'legacy'),
      row.target_entity ?? row.entity_id ?? null,
      row.target_id ?? row.record_id ?? null,
      String(row.outcome ?? 'allowed'),
      row.cause ?? null,
      row.idempotency_key ?? null,
      row.before_json ?? null,
      row.after_json ?? row.details_json ?? null,
      manifest.irFingerprint,
      String(row.created_at ?? nowIso())
    );
  }
  db.exec('DROP TABLE "' + temp + '"');
}

function ensureIdempotencyTable(){
  db.exec('CREATE TABLE IF NOT EXISTS "' + IDEMPOTENCY_TABLE + '" ("scope" TEXT NOT NULL,"operation_key" TEXT NOT NULL,"request_fingerprint" TEXT NOT NULL,"record_id" TEXT NOT NULL,"status_code" INTEGER NOT NULL,"response_json" TEXT NOT NULL,PRIMARY KEY ("scope","operation_key"))');
}

async function initialize(){
  db.exec(normalizeMigrationSql(migrationSql));
  db.exec('CREATE TABLE IF NOT EXISTS "' + META_TABLE + '" ("key" TEXT PRIMARY KEY,"value" TEXT NOT NULL)');
  ensureIdempotencyTable();
  ensureAuditTable();
  if (SECURITY_SCHEMA.authentication) {
    ensureAccountsTable();
    ensureSessionsTable();
    await bootstrapFirstAccount();
  }
  setMeta('irFingerprint', manifest.irFingerprint);
}

function roleName(roleId){
  const role = (SECURITY_SCHEMA.roles ?? []).find((candidate) => candidate.id === roleId);
  return role ? role.name : roleId;
}

const routes = [];
function route(method, pattern, handler){
  routes.push({ method, pattern, handler });
}

route('GET', new RegExp('^/$'), async (_req, res) => {
  html(res, INDEX_HTML);
});

route('GET', new RegExp('^/index\\\\.html$'), async (_req, res) => {
  html(res, INDEX_HTML);
});

route('GET', new RegExp('^/app\\\\.js$'), async (_req, res) => {
  text(res, 200, 'application/javascript; charset=utf-8', APP_JS);
});

route('GET', new RegExp('^/styles\\\\.css$'), async (_req, res) => {
  text(res, 200, 'text/css; charset=utf-8', STYLES_CSS);
});

route('GET', new RegExp('^/favicon\\\\.ico$'), async (_req, res) => {
  res.writeHead(204, { 'Cache-Control': 'no-store' });
  res.end();
});

route('POST', new RegExp('^/auth/login$'), async (req, res) => {
  if (!SECURITY_SCHEMA.authentication) {
    json(res, 404, { code: 'NOT_FOUND', error: 'Not found' });
    return;
  }
  const originError = requireSameOrigin(req);
  if (originError) {
    json(res, originError.status, originError.body);
    return;
  }
  const body = await readBody(req).catch((error) => {
    void error;
    return null;
  });
  if (!body) {
    json(res, 401, { code: 'INVALID_CREDENTIALS', error: 'INVALID_CREDENTIALS' });
    return;
  }
  const config = authConfig();
  const email = normalizeEmail(body.email);
  const password = String(body.password ?? '');
  const remote = String(req.socket.remoteAddress ?? '');
  if (!loginAllowed(email, remote)) {
    auditLog({ operation: 'auth.login', targetEntity: config.identityEntity.id, outcome: 'denied', cause: 'rate-limited', after: { identity_email: email } });
    json(res, 401, { code: 'INVALID_CREDENTIALS', error: 'INVALID_CREDENTIALS' });
    return;
  }
  const identity = db.prepare(
    'SELECT i.*, a."role_id", a."password_salt", a."password_hash", a."scrypt_n", a."scrypt_r", a."scrypt_p", a."scrypt_keylen", a."disabled" FROM "' + config.identityTable + '" i JOIN "' + ACCOUNTS_TABLE + '" a ON a."identity_id" = i."id" WHERE lower(i."' + config.identityField.name + '") = ?'
  ).get(email);
  if (!identity || Number(identity.disabled) === 1) {
    auditLog({ operation: 'auth.login', targetEntity: config.identityEntity.id, targetId: identity ? String(identity.id) : null, outcome: 'denied', cause: 'invalid-credentials', after: { identity_email: email } });
    json(res, 401, { code: 'INVALID_CREDENTIALS', error: 'INVALID_CREDENTIALS' });
    return;
  }
  const computed = await passwordHash(password, String(identity.password_salt), {
    N: Number(identity.scrypt_n),
    r: Number(identity.scrypt_r),
    p: Number(identity.scrypt_p),
    keylen: Number(identity.scrypt_keylen)
  });
  const left = Buffer.from(computed, 'hex');
  const right = Buffer.from(String(identity.password_hash), 'hex');
  if (left.length !== right.length || !timingSafeEqual(left, right)) {
    auditLog({ operation: 'auth.login', targetEntity: config.identityEntity.id, targetId: String(identity.id), outcome: 'denied', cause: 'invalid-credentials', after: { identity_email: email } });
    json(res, 401, { code: 'INVALID_CREDENTIALS', error: 'INVALID_CREDENTIALS' });
    return;
  }
  const sessionToken = randomBytes(32).toString('hex');
  const sessionHash = sha256(sessionToken);
  const csrfToken = randomBytes(16).toString('hex');
  const csrfHash = sha256(csrfToken);
  const now = nowIso();
  const expiresAt = new Date(Date.now() + SESSION_MAX_AGE_SECONDS * 1000).toISOString();
  const openSessions = db.prepare('SELECT "token_hash" FROM "' + SESSIONS_TABLE + '" WHERE "identity_id"=? AND "revoked_at" IS NULL').all(String(identity.id));
  db.exec('BEGIN');
  try {
    for (const prior of openSessions) {
      clearSessionMemory(String(prior.token_hash));
    }
    db.prepare('UPDATE "' + SESSIONS_TABLE + '" SET "revoked_at"=? WHERE "identity_id"=? AND "revoked_at" IS NULL').run(now, String(identity.id));
    db.prepare(
      'INSERT INTO "' + SESSIONS_TABLE + '" ("token_hash","csrf_token_hash","identity_id","role_id","expires_at","created_at","last_seen_at","revoked_at") VALUES (?,?,?,?,?,?,?,NULL)'
    ).run(sessionHash, csrfHash, String(identity.id), String(identity.role_id), expiresAt, now, now);
    auditLog({
      actorIdentityId: String(identity.id),
      actorRoleId: String(identity.role_id),
      operation: 'auth.login',
      targetEntity: config.identityEntity.id,
      targetId: String(identity.id),
      outcome: 'allowed',
      after: {
        identity_id: String(identity.id),
        role_id: String(identity.role_id),
        identity_email: String(identity[config.identityField.name] ?? ''),
        identity_name: String(identity.name ?? '')
      }
    });
    db.exec('COMMIT');
  } catch (error) {
    db.exec('ROLLBACK');
    throw error;
  }
  rememberCsrf(sessionHash, csrfToken);
  json(res, 200, {
    identity_id: String(identity.id),
    role_id: String(identity.role_id),
    identity_email: String(identity[config.identityField.name] ?? ''),
    identity_name: String(identity.name ?? ''),
    csrf_token: csrfToken
  }, { 'Set-Cookie': sessionCookieHeader(sessionToken, SESSION_MAX_AGE_SECONDS) });
});

route('GET', new RegExp('^/auth/me$'), async (req, res) => {
  if (!SECURITY_SCHEMA.authentication) {
    json(res, 404, { code: 'NOT_FOUND', error: 'Not found' });
    return;
  }
  const session = validateSession(req);
  if (!session) {
    json(res, 401, { code: 'UNAUTHORIZED', error: 'Unauthorized' });
    return;
  }
  const config = authConfig();
  const identity = db.prepare('SELECT * FROM "' + config.identityTable + '" WHERE "id"=?').get(session.identity_id);
  if (!identity) {
    json(res, 401, { code: 'UNAUTHORIZED', error: 'Unauthorized' });
    return;
  }
  const csrfToken = ensureCsrfToken(session);
  json(res, 200, {
    identity_id: session.identity_id,
    role_id: session.role_id,
    csrf_token: csrfToken,
    identity_email: String(identity[config.identityField.name] ?? ''),
    identity_name: String(identity.name ?? ''),
    permissions: effectivePermissions(session.role_id)
  });
});

route('POST', new RegExp('^/auth/logout$'), async (req, res) => {
  if (!SECURITY_SCHEMA.authentication) {
    json(res, 404, { code: 'NOT_FOUND', error: 'Not found' });
    return;
  }
  const session = validateSession(req);
  if (!session) {
    json(res, 401, { code: 'UNAUTHORIZED', error: 'Unauthorized' });
    return;
  }
  const originError = requireSameOrigin(req);
  if (originError) {
    json(res, originError.status, originError.body);
    return;
  }
  const csrfError = validateCsrf(session, req);
  if (csrfError) {
    json(res, csrfError.status, csrfError.body);
    return;
  }
  db.prepare('UPDATE "' + SESSIONS_TABLE + '" SET "revoked_at"=? WHERE "token_hash"=?').run(nowIso(), session.token_hash);
  clearSessionMemory(session.token_hash);
  auditLog({
    actorIdentityId: session.identity_id,
    actorRoleId: session.role_id,
    operation: 'auth.logout',
    targetEntity: SECURITY_SCHEMA.authentication.identityEntityId,
    targetId: session.identity_id,
    outcome: 'allowed'
  });
  json(res, 200, { ok: true }, { 'Set-Cookie': sessionCookieHeader('', 0) });
});

route('POST', new RegExp('^/auth/accounts$'), async (req, res) => {
  if (!SECURITY_SCHEMA.authentication) {
    json(res, 404, { code: 'NOT_FOUND', error: 'Not found' });
    return;
  }
  const session = validateSession(req);
  if (!session) {
    json(res, 401, { code: 'UNAUTHORIZED', error: 'Unauthorized' });
    return;
  }
  const originError = requireSameOrigin(req);
  if (originError) {
    json(res, originError.status, originError.body);
    return;
  }
  const csrfError = validateCsrf(session, req);
  if (csrfError) {
    json(res, csrfError.status, csrfError.body);
    return;
  }
  const authz = authorize(session, 'provision', '', undefined, undefined);
  if (!authz.allowed) {
    auditLog({ actorIdentityId: session.identity_id, actorRoleId: session.role_id, operation: 'auth.provision', outcome: 'denied', cause: 'forbidden' });
    json(res, 403, { code: 'FORBIDDEN', error: 'Forbidden' });
    return;
  }
  const body = await readBody(req).catch((error) => {
    void error;
    return null;
  });
  if (!body) {
    json(res, 400, { code: 'VALIDATION_ERROR', error: 'Request body must be valid JSON.' });
    return;
  }
  const config = authConfig();
  const idemKey = typeof body.idempotency_key === 'string' && body.idempotency_key !== ''
    ? body.idempotency_key
    : typeof req.headers['idempotency-key'] === 'string' && req.headers['idempotency-key'] !== ''
      ? req.headers['idempotency-key']
      : '';
  if (!idemKey) {
    json(res, 400, { code: 'MISSING_IDEMPOTENCY_KEY', error: 'idempotency_key is required.' });
    return;
  }
  const roleId = String(body.role_id ?? '');
  const role = (SECURITY_SCHEMA.roles ?? []).find((candidate) => candidate.id === roleId);
  const email = normalizeEmail(body[config.identityField.name]);
  const name = String(body.name ?? '').trim();
  const password = String(body.password ?? '');
  if (!email || !name || password.length < 12 || !role) {
    json(res, 400, { code: 'VALIDATION_ERROR', error: 'Invalid account payload.' });
    return;
  }
  const scope = 'auth.accounts';
  const operationKey = session.identity_id + ':' + idemKey;
  const fingerprint = sha256(JSON.stringify({
    identity: sanitizeAuditPayload(Object.fromEntries(config.identityEntity.fields.map((field) => [field.name, field.name === config.identityField.name ? email : body[field.name]]))),
    role_id: role.id,
    password_sha256: sha256(password)
  }));
  if (replayIdempotency(res, scope, operationKey, fingerprint)) {
    return;
  }
  let identityValues;
  try {
    identityValues = buildIdentityValues(body);
  } catch (error) {
    const message = String(error instanceof Error ? error.message : error);
    if (message.startsWith('VALIDATION_ERROR:')) {
      json(res, 400, { code: 'VALIDATION_ERROR', error: 'Invalid account payload.' });
      return;
    }
    throw error;
  }
  const salt = randomBytes(32).toString('hex');
  const hash = await passwordHash(password, salt);
  const responseBody = { data: { id: identityValues.identityId, role_id: role.id } };
  db.exec('BEGIN');
  try {
    db.prepare('INSERT INTO "' + identityValues.config.identityTable + '" (' + identityValues.columns.map((column) => '"' + column + '"').join(',') + ') VALUES (' + identityValues.columns.map(() => '?').join(',') + ')').run(...identityValues.values);
    db.prepare(
      'INSERT INTO "' + ACCOUNTS_TABLE + '" ("identity_id","role_id","password_salt","password_hash","scrypt_n","scrypt_r","scrypt_p","scrypt_keylen","password_version","disabled","created_at","updated_at") VALUES (?,?,?,?,16384,8,1,64,1,0,?,?)'
    ).run(identityValues.identityId, role.id, salt, hash, identityValues.now, identityValues.now);
    storeIdempotency(scope, operationKey, fingerprint, identityValues.identityId, 200, responseBody);
    auditLog({
      actorIdentityId: session.identity_id,
      actorRoleId: session.role_id,
      operation: 'auth.provision',
      targetEntity: identityValues.config.identityEntity.id,
      targetId: identityValues.identityId,
      outcome: 'allowed',
      idempotencyKey: idemKey,
      after: {
        identity_id: identityValues.identityId,
        role_id: role.id,
        identity_email: email,
        identity_name: name
      }
    });
    db.exec('COMMIT');
  } catch (error) {
    db.exec('ROLLBACK');
    if (String(error instanceof Error ? error.message : error).includes('UNIQUE constraint failed')) {
      json(res, 409, { code: 'UNIQUE_CONFLICT', entity: identityValues.config.identityEntity.name, field: identityValues.config.identityField.name, error: identityValues.config.identityField.name + ' is already in use.' });
      return;
    }
    throw error;
  }
  json(res, 201, responseBody);
});

for (const entity of SECURITY_SCHEMA.entities) {
  const table = ENTITY_TABLES[entity.id];
  route('GET', new RegExp('^/' + table + '$'), async (req, res) => {
    const session = validateSession(req);
    if (SECURITY_SCHEMA.authentication && !session) {
      json(res, 401, { code: 'UNAUTHORIZED', error: 'Unauthorized' });
      return;
    }
    const authz = authorize(session, 'read', entity.id, undefined, undefined);
    if (!authz.allowed) {
      json(res, 403, { code: 'FORBIDDEN', error: 'Forbidden' });
      return;
    }
    const where = session ? effectiveWhere(session, entity.id) : { sql: '', params: [] };
    const sql = 'SELECT * FROM "' + table + '"' + (where.sql ? ' WHERE ' + where.sql : '') + ' ORDER BY "created_at" ASC';
    const rows = db.prepare(sql).all(...where.params);
    json(res, 200, { data: rows });
  });

  route('GET', new RegExp('^/' + table + '/(?<id>[^/]+)$'), async (req, res, params) => {
    const session = validateSession(req);
    if (SECURITY_SCHEMA.authentication && !session) {
      json(res, 401, { code: 'UNAUTHORIZED', error: 'Unauthorized' });
      return;
    }
    const row = db.prepare('SELECT * FROM "' + table + '" WHERE "id"=?').get(params.id);
    if (!row) {
      json(res, 404, { code: 'NOT_FOUND', error: 'Not found' });
      return;
    }
    const authz = authorize(session, 'read', entity.id, undefined, row);
    if (!authz.allowed) {
      json(res, 404, { code: 'NOT_FOUND', error: 'Not found' });
      return;
    }
    json(res, 200, { data: row });
  });

  route('POST', new RegExp('^/' + table + '$'), async (req, res) => {
    const originError = requireSameOrigin(req);
    if (originError) {
      json(res, originError.status, originError.body);
      return;
    }
    const idemKey = typeof req.headers['idempotency-key'] === 'string' ? req.headers['idempotency-key'] : '';
    if (!idemKey) {
      json(res, 400, { code: 'MISSING_IDEMPOTENCY_KEY', error: 'Idempotency-Key header is required for create operations. Generate a UUID v4 for each new create dialog.' });
      return;
    }
    const session = validateSession(req);
    if (SECURITY_SCHEMA.authentication && !session) {
      json(res, 401, { code: 'UNAUTHORIZED', error: 'Unauthorized' });
      return;
    }
    if (SECURITY_SCHEMA.authentication) {
      const csrfError = validateCsrf(session, req);
      if (csrfError) {
        json(res, csrfError.status, csrfError.body);
        return;
      }
    }
    const authz = authorize(session, 'create', entity.id, undefined, undefined);
    if (!authz.allowed) {
      json(res, 403, { code: 'FORBIDDEN', error: 'Forbidden' });
      return;
    }
    const body = await readBody(req).catch((error) => {
      void error;
      return null;
    });
    if (!body) {
      json(res, 400, { code: 'VALIDATION_ERROR', error: 'Request body must be valid JSON.' });
      return;
    }
    if (authz.forceOwner && session) {
      body.owner_id = session.identity_id;
    }
    const scope = 'entity.create:' + entity.id;
    const operationKey = session ? session.identity_id + ':' + idemKey : idemKey;
    const fingerprint = sha256(JSON.stringify(body));
    if (replayIdempotency(res, scope, operationKey, fingerprint)) {
      return;
    }
    const id = randomUUID();
    const now = nowIso();
    const columns = ['id', 'created_at', 'updated_at', 'version'];
    const values = [id, now, now, 1];
    for (const field of entity.fields) {
      columns.push(field.name);
      if (body[field.name] !== undefined) {
        values.push(typedFieldValue(field, body[field.name]));
      } else if (field.default !== undefined) {
        values.push(typedFieldValue(field, field.default));
      } else {
        values.push(null);
      }
    }
    for (const relationship of (SECURITY_SCHEMA.relationships ?? []).filter((candidate) => candidate.fromEntityId === entity.id)) {
      const column = relationship.name + '_id';
      columns.push(column);
      if (relationship.name === 'owner' && authz.forceOwner && session) {
        values.push(session.identity_id);
      } else {
        values.push(body[column] ?? null);
      }
    }
    let created;
    const responseBody = { data: null };
    db.exec('BEGIN');
    try {
      db.prepare('INSERT INTO "' + table + '" (' + columns.map((column) => '"' + column + '"').join(',') + ') VALUES (' + columns.map(() => '?').join(',') + ')').run(...values);
      created = db.prepare('SELECT * FROM "' + table + '" WHERE "id"=?').get(id);
      responseBody.data = created;
      storeIdempotency(scope, operationKey, fingerprint, id, 200, responseBody);
      auditLog({
        actorIdentityId: session ? session.identity_id : null,
        actorRoleId: session ? session.role_id : null,
        operation: 'entity.create',
        targetEntity: entity.id,
        targetId: id,
        outcome: 'allowed',
        idempotencyKey: idemKey,
        after: created
      });
      db.exec('COMMIT');
    } catch (error) {
      db.exec('ROLLBACK');
      const message = String(error instanceof Error ? error.message : error);
      if (message.includes('UNIQUE constraint failed')) {
        const uniqueField = entity.fields.find((field) => field.unique && message.includes('.' + field.name))?.name ?? '';
        json(res, 409, {
          code: 'UNIQUE_CONFLICT',
          entity: entity.name,
          field: uniqueField,
          error: uniqueField ? uniqueField + ' is already in use.' : 'A unique value already exists.'
        });
        return;
      }
      throw error;
    }
    json(res, 201, responseBody);
  });

  route('PUT', new RegExp('^/' + table + '/(?<id>[^/]+)$'), async (req, res, params) => {
    const originError = requireSameOrigin(req);
    if (originError) {
      json(res, originError.status, originError.body);
      return;
    }
    const session = validateSession(req);
    if (SECURITY_SCHEMA.authentication && !session) {
      json(res, 401, { code: 'UNAUTHORIZED', error: 'Unauthorized' });
      return;
    }
    if (SECURITY_SCHEMA.authentication) {
      const csrfError = validateCsrf(session, req);
      if (csrfError) {
        json(res, csrfError.status, csrfError.body);
        return;
      }
    }
    const existing = db.prepare('SELECT * FROM "' + table + '" WHERE "id"=?').get(params.id);
    if (!existing) {
      json(res, 404, { code: 'NOT_FOUND', error: 'Not found' });
      return;
    }
    const authz = authorize(session, 'update', entity.id, undefined, existing);
    if (!authz.allowed) {
      json(res, 404, { code: 'NOT_FOUND', error: 'Not found' });
      return;
    }
    const body = await readBody(req).catch((error) => {
      void error;
      return null;
    });
    if (!body || !Number.isInteger(body.expectedVersion)) {
      json(res, 400, { code: 'VALIDATION_ERROR', error: 'expectedVersion must be an integer' });
      return;
    }
    if (body.owner_id !== undefined && body.owner_id !== existing.owner_id) {
      json(res, 400, { code: 'VALIDATION_ERROR', error: 'Cannot change owner' });
      return;
    }
    const sets = [];
    const values = [];
    for (const field of entity.fields) {
      if (body[field.name] !== undefined) {
        sets.push('"' + field.name + '"=?');
        values.push(typedFieldValue(field, body[field.name]));
      }
    }
    for (const relationship of (SECURITY_SCHEMA.relationships ?? []).filter((candidate) => candidate.fromEntityId === entity.id)) {
      const column = relationship.name + '_id';
      if (relationship.name === 'owner') {
        continue;
      }
      if (body[column] !== undefined) {
        sets.push('"' + column + '"=?');
        values.push(body[column]);
      }
    }
    sets.push('"updated_at"=?');
    values.push(nowIso());
    const result = db.prepare('UPDATE "' + table + '" SET ' + sets.join(',') + ', "version" = "version" + 1 WHERE "id"=? AND "version"=?').run(...values, params.id, body.expectedVersion);
    if (Number(result.changes) === 0) {
      json(res, 409, { code: 'VERSION_CONFLICT', error: 'The record was modified since last read.' });
      return;
    }
    const updated = db.prepare('SELECT * FROM "' + table + '" WHERE "id"=?').get(params.id);
    auditLog({
      actorIdentityId: session ? session.identity_id : null,
      actorRoleId: session ? session.role_id : null,
      operation: 'entity.update',
      targetEntity: entity.id,
      targetId: String(params.id),
      outcome: 'allowed',
      before: existing,
      after: updated
    });
    json(res, 200, { data: updated });
  });
}

for (const action of SECURITY_SCHEMA.actions ?? []) {
  const entity = SECURITY_SCHEMA.entities.find((candidate) => candidate.id === action.entityId);
  if (!entity) {
    continue;
  }
  const table = ENTITY_TABLES[entity.id];
  route('POST', new RegExp('^/' + table + '/(?<id>[^/]+)/actions/' + action.name + '$'), async (req, res, params) => {
    const originError = requireSameOrigin(req);
    if (originError) {
      json(res, originError.status, originError.body);
      return;
    }
    const idemKey = typeof req.headers['idempotency-key'] === 'string' ? req.headers['idempotency-key'] : '';
    if (!idemKey) {
      json(res, 400, { code: 'MISSING_IDEMPOTENCY_KEY', error: 'Idempotency-Key header is required for action operations. Generate a UUID v4 for each action click.' });
      return;
    }
    const session = validateSession(req);
    if (SECURITY_SCHEMA.authentication && !session) {
      json(res, 401, { code: 'UNAUTHORIZED', error: 'Unauthorized' });
      return;
    }
    if (SECURITY_SCHEMA.authentication) {
      const csrfError = validateCsrf(session, req);
      if (csrfError) {
        json(res, csrfError.status, csrfError.body);
        return;
      }
    }
    const body = await readBody(req).catch((error) => {
      void error;
      return null;
    });
    if (!body || !Number.isInteger(body.expectedVersion)) {
      json(res, 400, { code: 'VALIDATION_ERROR', error: 'expectedVersion must be an integer' });
      return;
    }
    const scope = 'entity.action:' + entity.id + ':' + action.id + ':' + String(params.id);
    const operationKey = session ? session.identity_id + ':' + idemKey : idemKey;
    const fingerprint = sha256(JSON.stringify(body));
    if (replayIdempotency(res, scope, operationKey, fingerprint)) {
      return;
    }
    db.exec('BEGIN');
    try {
      const row = db.prepare('SELECT * FROM "' + table + '" WHERE "id"=?').get(params.id);
      if (!row) {
        db.exec('ROLLBACK');
        json(res, 404, { code: 'NOT_FOUND', error: 'Not found' });
        return;
      }
      const authz = authorize(session, 'run', entity.id, action.id, row);
      if (!authz.allowed) {
        db.exec('ROLLBACK');
        json(res, 404, { code: 'NOT_FOUND', error: 'Not found' });
        return;
      }
      if (Number(row.version) !== body.expectedVersion) {
        db.exec('ROLLBACK');
        json(res, 409, { code: 'VERSION_CONFLICT', error: 'The record was modified since last read.' });
        return;
      }
      for (const precondition of action.preconditions) {
        const left = row[precondition.fieldName];
        const normalizedLeft = typeof precondition.value === 'boolean' ? Boolean(left) : left;
        if (precondition.operator === 'is' && normalizedLeft !== precondition.value) {
          db.exec('ROLLBACK');
          json(res, 409, { code: 'PRECONDITION_FAILED', action: action.id, actionName: action.name, error: precondition.message });
          return;
        }
        if (precondition.operator === 'is not' && normalizedLeft === precondition.value) {
          db.exec('ROLLBACK');
          json(res, 409, { code: 'PRECONDITION_FAILED', action: action.id, actionName: action.name, error: precondition.message });
          return;
        }
        if (precondition.operator === 'is greater than' && !(Number(normalizedLeft) > Number(precondition.value))) {
          db.exec('ROLLBACK');
          json(res, 409, { code: 'PRECONDITION_FAILED', action: action.id, actionName: action.name, error: precondition.message });
          return;
        }
        if (precondition.operator === 'is at least' && !(Number(normalizedLeft) >= Number(precondition.value))) {
          db.exec('ROLLBACK');
          json(res, 409, { code: 'PRECONDITION_FAILED', action: action.id, actionName: action.name, error: precondition.message });
          return;
        }
        if (precondition.operator === 'is less than' && !(Number(normalizedLeft) < Number(precondition.value))) {
          db.exec('ROLLBACK');
          json(res, 409, { code: 'PRECONDITION_FAILED', action: action.id, actionName: action.name, error: precondition.message });
          return;
        }
        if (precondition.operator === 'is at most' && !(Number(normalizedLeft) <= Number(precondition.value))) {
          db.exec('ROLLBACK');
          json(res, 409, { code: 'PRECONDITION_FAILED', action: action.id, actionName: action.name, error: precondition.message });
          return;
        }
      }
      const sets = [];
      const values = [];
      for (const assignment of action.assignments) {
        const field = entity.fields.find((candidate) => candidate.name === assignment.fieldName);
        sets.push('"' + assignment.fieldName + '"=?');
        values.push(field && field.type === 'boolean' ? (assignment.value ? 1 : 0) : assignment.value);
      }
      sets.push('"updated_at"=?');
      values.push(nowIso());
      const result = db.prepare('UPDATE "' + table + '" SET ' + sets.join(',') + ', "version" = "version" + 1 WHERE "id"=? AND "version"=?').run(...values, params.id, body.expectedVersion);
      if (Number(result.changes) === 0) {
        db.exec('ROLLBACK');
        json(res, 409, { code: 'VERSION_CONFLICT', error: 'The record was modified since last read.' });
        return;
      }
      const updated = db.prepare('SELECT * FROM "' + table + '" WHERE "id"=?').get(params.id);
      const responseBody = { data: updated };
      storeIdempotency(scope, operationKey, fingerprint, String(params.id), 200, responseBody);
      auditLog({
        actorIdentityId: session ? session.identity_id : null,
        actorRoleId: session ? session.role_id : null,
        operation: 'entity.action',
        targetEntity: entity.id,
        targetId: String(params.id),
        outcome: 'allowed',
        idempotencyKey: idemKey,
        before: row,
        after: updated
      });
      db.exec('COMMIT');
      json(res, 200, responseBody);
    } catch (error) {
      db.exec('ROLLBACK');
      throw error;
    }
  });
}

const server = createServer(async (req, res) => {
  const method = req.method ?? 'GET';
  const pathname = new URL(req.url ?? '/', 'http://127.0.0.1:' + PORT).pathname;
  for (const candidate of routes) {
    if (candidate.method !== method) {
      continue;
    }
    const match = candidate.pattern.exec(pathname);
    if (!match) {
      continue;
    }
    try {
      await candidate.handler(req, res, match.groups ?? {});
    } catch (error) {
      console.error(error);
      json(res, 500, { code: 'INTERNAL_ERROR', error: 'Internal server error' });
    }
    return;
  }
  json(res, 404, { code: 'NOT_FOUND', error: 'Not found' });
});

server.listen(PORT, '127.0.0.1', () => {
  console.log('IntentLang server listening on http://127.0.0.1:' + PORT);
});
`;

  const packageJson =
    JSON.stringify(
      {
        name: ir.application.id,
        version: "1.0.0",
        type: "module",
        scripts: { start: "node app.mjs" }
      },
      null,
      2
    ) + "\n";

  return { appMjs, packageJson };
}
